name: deploy

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker pull ghcr.io/nasjp/dockerimages/rust-wasm-pack:latest
    - run: docker run -v $PWD:/app --workdir=/app ghcr.io/nasjp/dockerimages/rust-wasm-pack:latest bash -c "wasm-pack build --target web --out-name wasm --out-dir public --no-typescript"
    - run: sudo rm -f public/.gitignore
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
